apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: __YOUR_NAME__
  name: __YOUR_NAME__-ambassador
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ambassador
            port:
              number: 8080
    host: "__YOUR_NAME__-amb.workshop.demomrvn.online"
---
apiVersion: v1
kind: Service
metadata:
  namespace: __YOUR_NAME__
  name: ambassador
spec:
  type: ClusterIP
  selector:
    app: ambassador
  ports:
    - name: ambassador
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  namespace: __YOUR_NAME__
  name: ambassador
  labels:
    app: ambassador
spec:
  containers:
  - name: main
    image: pnk8s101/http-post-sender:v1
    imagePullPolicy: IfNotPresent
    env:
    - name: AMBASSADOR_URL
      value: http://localhost:9088
    ports:
     - containerPort: 8080
       protocol: TCP
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "32Mi"
        cpu: "50m"
  - name: ambassador
    image: pnk8s101/ambassador:v1.2
    imagePullPolicy: IfNotPresent
    env:
    - name: ENV
      value: dev
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "100m"
