apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: NodePort
  selector:
    app: ambassador
  ports:
    - name: ambassador
      protocol: TCP
      port: 8080
      nodePort: 30447
---
apiVersion: v1
kind: Pod
metadata:
  name: ambassador
  labels:
    app: ambassador
spec:
  containers:
  - name: main
    # http post to http://localhost:9088
    # php > bash > curl
    image: trafex/php-nginx:2.2.0
    imagePullPolicy: IfNotPresent
    env:
    - name: AMBASSADOR_URL
      value: http://localhost:9088
    ports:
     - containerPort: 8080
       protocol: TCP
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  - name: ambassador
    image: pnk8s101/ambassador
    imagePullPolicy: IfNotPresent
    env:
    - name: ENV
      value: dev
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "250m"
