apiVersion: v1
kind: ConfigMap
metadata:
  name: production-the-map
data:
  altGreeting: "Production is HERE!"
  enableRisky: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-the-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: the-container
        image: pnk8s101/hello:2
        command: ["/hello",
                  "--port=8080",
                  "--enableRiskyFeature=$(ENABLE_RISKY)"]
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: production-the-map
              key: altGreeting
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: production-the-map
              key: enableRisky
      - name: watch-the-container
        image: curlimages/curl:7.78.0
        command: ["watch", "-n", "10",
                  "curl", "localhost:8080" ]
        imagePullPolicy: IfNotPresent

---
kind: Service
apiVersion: v1
metadata:
  name: production-the-service
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
