---
apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: __YOUR_NAME__
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-external
  namespace: __YOUR_NAME__
subsets:
  - addresses:
      # 這個 ip 指向的是我們在 GKE 旁邊建的 redis 
      - ip: 10.3.0.3
    ports:
      - port: 6379