namePrefix: staging-
commonLabels:
  variant: staging
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am staging!
bases:
- ../base
patchesStrategicMerge:
- patch.yaml
#patches:
#- path: patch.yaml
#  target:
#    kind: Deployment
