apiVersion: v1
kind: Service
metadata:
  name: sidecar
spec:
  type: NodePort
  selector:
    app: sidecar
  ports:
    - name: sidecar
      protocol: TCP
      nodePort: 30443
      port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    app: sidecar
spec:
  initContainers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "echo '<html><h2>A simple container for sidecar testing.</h2><html>' >> /work-dir/index.html"]
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  containers:
  - name: nginx
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    - name: workdir
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  - name: sidecar
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    command: ["sh","-c","apk add coreutils; tail -f /var/log/nginx/access.log /var/log/nginx/error.log | stdbuf -oL cat"]
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  volumes:
    - name: shared-logs
      emptyDir: {}
    - name: workdir
      emptyDir: {}