apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-configmap
data:
  csv: |+
    album, year, US_peak_chart_post
    The White Stripes, 1999, -
    De Stijl, 2000, -
    White Blood Cells, 2001, 61
    Elephant, 2003, 6
    Get Behind Me Satan, 2005, 3
    Icky Thump, 2007, 2
    Under Great White Northern Lights, 2010, 11
    Live in Mississippi, 2011, -
    Live at the Gold Dollar, 2012, -
    Nine Miles from the White City, 2013, -
---
apiVersion: v1
kind: Service
metadata:
  name: adapter
spec:
  type: NodePort
  selector:
    app: adapter
  ports:
    - name: adapter
      protocol: TCP
      nodePort: 30445
      port: 80
    - name: adapter-sidecar
      protocol: TCP
      nodePort: 30446
      port: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: adapter
  labels:
    app: adapter
spec:
  initContainers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "cat /etc/csv/csv >> /work-dir/index.html"]
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
    - name: csv
      mountPath: "/etc/csv"
  containers:
  - name: nginx
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  - name: adapter
    image: python:alpine
    imagePullPolicy: IfNotPresent
    workingDir: /root
    command: ["/bin/sh", "-c"]
    args: ["apk add curl yq; curl -s http://localhost | python -c 'import csv, json, sys; print(json.dumps([dict(
r) for r in csv.DictReader(sys.stdin)]))' > index.html; cat index.html | yq e -P > yaml.html; python3 -m http.server 8080"]
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  volumes:
  - name: workdir
    emptyDir: {}
  - name: csv
    configMap:
      name: adapter-configmap
