apiVersion: v1
kind: ConfigMap
metadata:
  name: uat-the-map
data:
  altGreeting: "Good Morning! UAT!"
  enableRisky: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uat-the-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: the-container
        image: monopole/hello:1
        command: ["/hello",
                  "--port=8080",
                  "--enableRiskyFeature=$(ENABLE_RISKY)"]
        ports:
        - containerPort: 8080
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: uat-the-map
              key: altGreeting
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: uat-the-map
              key: enableRisky
---
kind: Service
apiVersion: v1
metadata:
  name: uat-the-service
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8080