apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: __YOUR_NAME__
  name: __YOUR_NAME__-init-1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: init-container-1
            port:
              number: 80
    host: "__YOUR_NAME__-init-1.workshop.demomrvn.online"
---
apiVersion: v1
kind: Service
metadata:
  namespace: __YOUR_NAME__
  name: init-container-1
spec:
  type: ClusterIP
  selector:
    app: init-container-1
  ports:
    - name: init-container-1
      protocol: TCP
      targetPort: 80
      port: 80
---
apiVersion: v1
kind: Pod
metadata:
  namespace: __YOUR_NAME__
  name: init-container-1
  labels:
    app: init-container-1
spec:
  # 在 Pod 內的所有 container 共享 volume
  volumes:
  - name: workdir
    emptyDir: {}
  # init container 區塊
  initContainers:
  - name: init1
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    # 撰寫一個簡單的 index.html
    args: ["-c", "echo '<html><h2>Hi, I am from Init container.</h2><html>' >> /work-dir/index.html"]
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  - name: init2
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "sleep 10"]
  # container 區塊
  containers:
  - name: main
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "32Mi"
        cpu: "50m"
